name: Build and Deploy Docker Image to Docker Hub (CD)

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.actor }} from build and push docker image job"
      - uses: actions/checkout@v5
      - name: Build Docker image and push to GitHub Registry (GitHub Packages)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ github.ref_name }}

  auto-deploy-docker-job:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    env:
      SERVER_IP: "157.90.230.179"
      SERVER_USER: "root"
      SERVER_PASSWORD: "bF9NN4xqsbmb"
      SERVER_PORT: 22
      CONTAINER_NAME: ${{ github.actor}}
      CONTAINER_PORT: 7354
      DOCKER_IMAGE_URL: "ghcr.io/${{ github.actor }}/${{ github.repository.name }}:${{ github.ref_name }}"
      # ใช้จริงต้องเก็บใน GitHub Secrets นะครับ
    steps:
      - run: echo "Hello, ${{ github.actor }} from auto deploy docker job"
      - name: Auto Deploy Docker Container
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ env.SERVER_IP}}
          username: ${{ env.SERVER_USER }}
          password: ${{ env.SERVER_PASSWORD }}
          port: ${{ env.SERVER_PORT }}
          script: |
            docker -v