name: Deploy to GitHub Pages (CD)

on:
  push:
    branches:
      - main # [ลบออกเมื่อใช้จริง]  # ติดตั้ง workflow นี้ให้ทำงานเมื่อมีการ push เข้าสาขาหลัก (main)
    tags:
      - "*.*.*" # ติดตั้ง workflow นี้ให้ทำงานเมื่อมีการ push tag ที่มีรูปแบบ x.y.z ตอน Release ใหม่


jobs:
  build-prod-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.actor }} from build prod job"
      - uses: actions/checkout@v5
      - name: Set Node.js version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run build production (create dist folder)
        run: npm run build
      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v5
        with:
          name: dist-production
          path: ./dist
        # ไปที่ Actions > Upload dist folder as artifact
        # เพื่อดาวน์โหลดไฟล์ (Artifact download URL จะได้ dist-production.zip)

  auto-deploy-job:
    runs-on: ubuntu-latest
    needs: build-prod-job
    # permissions:
    #   contents: write # เพื่อให้สามารถ deploy ไปที่ GitHub Pages ได้
    steps:
      - run: echo "Hello, ${{ github.actor }} from deploy job"
      - name: Download dist folder artifact
        uses: actions/download-artifact@v6
        with:
          name: dist-production
          path: ./dist
      - run: ls -la ./dist # ตรวจสอบไฟล์ในโฟลเดอร์ dist ที่ดาวน์โหลดมา
      - uses: actions/checkout@v5
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist       # โฟลเดอร์ output ของโปรเจกต์คุณ
          force_orphan: true        # (แนะนำ) ทำ branch ใหม่ให้สะอาด
      # - name: Publish to GitHub Pages
      #   uses: SerhiiKa/VuePagesAction@1.0.4
      #   with:
      #     username: ${{ github.actor }}
      #     reponame: ${{ github.event.repository.name }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
