name: Deploy to GitHub Pages (CD)

on:
  push:
    # branches:
    #   - main # [ลบออกเมื่อใช้จริง]  # ติดตั้ง workflow นี้ให้ทำงานเมื่อมีการ push เข้าสาขาหลัก (main)
    tags:
      - '*.*.*'  # ติดตั้ง workflow นี้ให้ทำงานเมื่อมีการ push tag ที่มีรูปแบบ x.y.z ตอน Release ใหม่

jobs:
  build-prod-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.actor }} from build prod job"
      - uses: actions/checkout@v5
      - name: Set Node.js version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run build production (create dist folder)
        run: npm run build
      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v5
        with:
          name: dist-production
          path: ./dist

  auto-deploy-job:
    runs-on: ubuntu-latest
    needs: build-prod-job
    steps:
      - run: echo "Hello, ${{ github.actor }} from deploy job"  