name: Git Workshop Demo CI

on:
  push:
    branches:
      - "feature/**"
      - "hotfix/**"
      - "fix/**"
      - "bugfix/**"
      - "chore/**"
      - "docs/**"
      - "refactor/**"
      - "style/**"
      - "test/**"
      - "perf/**"
      - "build/**"
      - "ci/**"
      - "revert/**"
      - main # อย่าลืมลบออก กรณีใช้งานจริง

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.actor }}"

      - uses: actions/checkout@v5

      - name: Set Node.js version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check lint
        run: npm run lint

  build-job:
    runs-on: ubuntu-latest
    needs: lint-job
    steps:
      - run: echo "Hello, ${{ github.actor }}"

      - uses: actions/checkout@v5

      - name: Set Node.js version to 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check build app
        run: npm run build